---
title: "Cell marker identification with seurat samples"
author: "Ronghui"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
library(Seurat)
library(patchwork)
mca.matrix <- readRDS(file = "/home/ronghui/project/scMarkerDetect/MCA/MCA_merged_mat.rds")
mca.metadata <- read.csv(file = "/home/ronghui/project/scMarkerDetect/MCA/MCA_All-batch-removed-assignments.csv", row.names = 1)

# 3896.0100681384406 minutes

```



```{r pressure, echo=FALSE, fig.height=9, fig.width=12}
mca <- CreateSeuratObject(counts = mca.matrix, meta.data = mca.metadata, project = "MouseCellAtlas")
# Only keep annotated cells
mca <- subset(mca, cells = names(which(!is.na(mca$ClusterID))))
# Leaves us with 242k cells
Idents(mca) <- "Tissue"
mca <- NormalizeData(mca, normalization.method = "LogNormalize", scale.factor = 10000)
mca.spleen <- subset(mca, idents = "Spleen")

unique(mca.spleen@active.ident)
rm(mca.matrix, mca.metadata)
```




```{r}
cell.anno <- read.csv(file=file.path("/home/ronghui/project/scMarkerDetect/MCA_CellAssignments.csv"))
cell.spleen <- cell.anno[grep("Spleen", cell.anno$Cell.name), ]
mca.spleen@meta.data$anno <- cell.spleen[match(colnames(mca.spleen), cell.spleen$Cell.name), ]$Annotation
Idents(mca.spleen) <- "anno"
Idents(mca.spleen) <- "anno"

mca.spleen@meta.data$anno.n <- as.numeric(Idents(mca.spleen))
table(mca.spleen$anno, mca.spleen$anno.n)
```


```{r}
De.spleen <-FindMarkers(mca.spleen, ident.1 = "Marginal zone B cell(Spleen)", test.use = "t")

De.spleen <- subset(De.spleen, p_val < 0.05)

get_split_pos.1(mca.spleen, "Cd22", "Marginal zone B cell(Spleen)")

df.b <- data.frame()
for (gene in rownames(De.spleen)) {
  df.s <- get_split_pos.2(mca.spleen, gene, "Marginal zone B cell(Spleen)", step = 0.01)
  df.b <- rbind(df.b, df.s)
}
df.b <- df.b[df.b$x.val != 0, ]
df.b$x.margin.adj.a <- df.b$x.margin.adj/df.b$x.val
df.b <- df.b[order(df.b$x.margin.adj, decreasing = T), ]


De.Macrophage <-FindMarkers(mca.spleen, ident.1 = "Macrophage(Spleen)", test.use = "t")

De.Macrophage <- subset(De.Macrophage, p_val < 0.05)
match("Cd14", rownames(De.Macrophage))

df.m <- data.frame()
for (gene in rownames(De.Macrophage)) {
  df.s <- get_split_pos.2(mca.spleen, gene, "Macrophage(Spleen)", step = 0.01)
  df.m <- rbind(df.m, df.s)
}
df.m <- df.m[df.m$x.val != 0, ]
df.m$x.margin.adj.a <- df.m$x.margin.adj/df.m$x.val
df.m <- df.m[order(df.m$x.margin.adj, decreasing = T), ]
df.m
match("Cd14", rownames(De.Macrophage))
match("Adgre1", rownames(De.Macrophage))
match("Cd14", rownames(df.m))

get_split_pos.2(mca.spleen, "Adgre1", "Macrophage(Spleen)")
VlnPlot(mca.spleen,"Adgre1")

De.tcell <-FindMarkers(mca.spleen, ident.1 = "T cell(Spleen)", test.use = "t")

De.tcell <- subset(De.tcell, p_val < 0.05)

df.t <- data.frame()
for (gene in rownames(De.tcell)) {
  df.s <- get_split_pos.2(mca.spleen, gene, "T cell(Spleen)", step = 0.01)
  df.t <- rbind(df.t, df.s)
}
df.t <- df.t[df.t$x.val != 0, ]
df.t$x.margin.adj.a <- df.t$x.margin.adj/df.t$x.val
df.t <- df.t[order(df.t$x.margin.adj, decreasing = T), ]
df.t

table(mca.spleen$anno, mca.spleen$anno.n)
df.b[order(df.b$x.margin.adj, decreasing = T), ]
VlnPlot(mca.spleen,"Cd19")
get_split_pos.1(mca.spleen, "Cd14", "Macrophage(Spleen)", step = 0.1)
Idents(mca.spleen) <- "anno"
pc1 <- FetchData(object = mca.spleen, vars = c('Ms4a1', "Cd14", 'ident'))
pc1
colnames(pc1) <- c("gene1", "gene2", "id")
pc1$gene1 <- normalize(pc1$gene1)

clusters <- c("T cell(Spleen)", "Macrophage(Spleen)", "Marginal zone B cell(Spleen)", "NK cell(Spleen)", "Dendritic cell_S100a4 high(Spleen)", "Dendritic cell_Siglech high(Spleen)")
Idents(mca.spleen) <- "anno"

markers.wilcox <- list()
markers.t <- list()
markers.MAST <- list()
markers.LR <- list()
for (x.cluster in clusters) {
  markers <- FindMarkers(mca.spleen, ident.1 = x.cluster, test.use = "t")
  markers.t[[x.cluster]] <- markers
  
  markers <- FindMarkers(mca.spleen, ident.1 = x.cluster, test.use = "wilcox")
  markers.wilcox[[x.cluster]] <- markers
  
  markers <- FindMarkers(mca.spleen, ident.1 = x.cluster, test.use = "MAST")
  markers.MAST[[x.cluster]] <- markers
  
  markers <- FindMarkers(mca.spleen, ident.1 = x.cluster, test.use = "LR")
  markers.LR[[x.cluster]] <- markers
}

t.genes <- c(match("Cd3d", rownames(markers.t[["T cell(Spleen)"]])), 
             match("Cd3e", rownames(markers.t[["T cell(Spleen)"]])), 
             match("Cd3g", rownames(markers.t[["T cell(Spleen)"]])))

wilcox.genes <- c(match("Cd3d", rownames(markers.wilcox[["T cell(Spleen)"]])),
                  match("Cd3e", rownames(markers.wilcox[["T cell(Spleen)"]])),
                  match("Cd3g", rownames(markers.wilcox[["T cell(Spleen)"]])))

mast.genes <- c(match("Cd3d", rownames(markers.MAST[["T cell(Spleen)"]])),
                match("Cd3e", rownames(markers.MAST[["T cell(Spleen)"]])),
                match("Cd3g", rownames(markers.MAST[["T cell(Spleen)"]])))

v.genes <- c(match("Cd3d", rownames(df.t)),
             match("Cd3e", rownames(df.t)),
             match("Cd3g", rownames(df.t)))
comet.genes <- c(24, 20, 2)


# T cells in spleen 

t.cells.genes <- c("Cd3d", "Cd3e", "Cd3g")

genes <- read.csv(paste("/home/ronghui/project/scMarkerDetect/output/data/cluster_4_singleton_all_ranked.csv"))
df <- data.frame()
for (gene in t.cells.genes) {
  df.s <- data.frame(t.test <- c(match(gene, rownames(markers.t[["T cell(Spleen)"]]))),
                   wilcox.test <- c(match(gene, rownames(markers.wilcox[["T cell(Spleen)"]]))),
                   mast <- c(match(gene, rownames(markers.MAST[["T cell(Spleen)"]]))),
                   LR <- c(match(gene, rownames(markers.LR[["T cell(Spleen)"]]))),
                   Comet <- c(match(toupper(gene), genes$gene_1)),
                   SD <- c(match(gene, rownames(df.t)))
                   )
  colnames(df.s) <- c("T-test", "Wilcox", "MAST", "LR", "Comet", "SD")
  rownames(df.s) <- paste(gene)
  df <- rbind(df, df.s)
}
df <- as.data.frame(t(df))
df$test.use <- rownames(df)
df$test.use  <- factor(df$test.use, levels = c("T-test", "Wilcox", "MAST", "LR", "Comet", "SD"))

library(ggplot2)

for (gene in t.cells.genes) {
  p <- ggplot(df, aes_string(x="test.use", y=paste(gene))) + 
    geom_bar(stat = "identity") +
  ggtitle(paste(gene, " in T cell (Spleen Tissue)"))
  print(p)
}
```

```{r}
# B cells in spleen 

t.cells.genes <- c("Ly6d", "Cd19", "Cd74", "Cd79b", "Ms4a1")

genes <- read.csv(paste("/home/ronghui/project/scMarkerDetect/output/data/cluster_5_singleton_all_ranked.csv"))
df <- data.frame()
for (gene in t.cells.genes) {
  df.s <- data.frame(t.test <- c(match(gene, rownames(markers.t[["Marginal zone B cell(Spleen)"]]))),
                   wilcox.test <- c(match(gene, rownames(markers.wilcox[["Marginal zone B cell(Spleen)"]]))),
                   mast <- c(match(gene, rownames(markers.MAST[["Marginal zone B cell(Spleen)"]]))),
                   LR <- c(match(gene, rownames(markers.LR[["Marginal zone B cell(Spleen)"]]))),
                   Comet <- c(grep(toupper(gene), genes$gene_1)),
                   SD <- c(match(gene, rownames(df.b)))
                   )
  colnames(df.s) <- c("T-test", "Wilcox", "MAST", "LR", "Comet", "SD")
  rownames(df.s) <- paste(gene)
  df <- rbind(df, df.s)
}
df <- as.data.frame(t(df))
df$test.use <- rownames(df)
df$test.use  <- factor(df$test.use, levels = c("T-test", "Wilcox", "MAST", "LR", "Comet", "SD"))

library(ggplot2)

for (gene in t.cells.genes) {
  p <- ggplot(df, aes_string(x="test.use", y=paste(gene))) + 
    geom_bar(stat = "identity") +
  ggtitle(paste(gene, " in T cell (Spleen Tissue)"))
  print(p)
}

markers.t[["Marginal zone B cell(Spleen)"]]$test.use <- "t.test"
markers.t[["Marginal zone B cell(Spleen)"]]$celltype <- "T cell"
markers.t[["Marginal zone B cell(Spleen)"]]$gene <- rownames(markers.t[["Marginal zone B cell(Spleen)"]])

ptm <- proc.time()
markers.t <- FindAllMarkers(mca.spleen, test.use = "t")
proc.time() - ptm

ptm <- proc.time()
markers.wilcox <- FindAllMarkers(mca.spleen, test.use = "wilcox")
proc.time() - ptm

ptm <- proc.time()
markers.MAST <- FindAllMarkers(mca.spleen, test.use = "MAST")
proc.time() - ptm

ptm <- proc.time()
markers.LR <- FindAllMarkers(mca.spleen, test.use = "LR")
proc.time() - ptm
markers.LR[markers.LR$cluster == "Marginal zone B cell(Spleen)", ]

De.spleen <-FindMarkers(mca.spleen, ident.1 = "Marginal zone B cell(Spleen)", test.use = "t")
De.spleen <- subset(De.spleen, p_val < 0.05)
De.spleen <- subset(De.spleen, avg_log2FC > 0)

expr.matrix <- mca.spleen@assays$RNA@data[rownames(De.spleen),]

De.spleen <-FindMarkers(mca.spleen, ident.1 = "T cell(Spleen)", test.use = "t")
De.spleen <- subset(De.spleen, p_val < 0.05)
# De.spleen <- subset(De.spleen, avg_log2FC > 0)

expr.matrix <- mca.spleen@assays$RNA@data[rownames(De.spleen),]

expr.matrix.1 <- apply(expr.matrix, 1, normalize)
expr.matrix.1 <- as.data.frame(expr.matrix.1)

expr.matrix.1$id <- as.character(mca.spleen@active.ident)

df.id <- expr.matrix.1[expr.matrix.1$id == "Marginal zone B cell(Spleen)", ]
df.other <- expr.matrix.1[expr.matrix.1$id != "Marginal zone B cell(Spleen)", ]

```


```{r}
# CD74	IGKC
# TRAC	IGKC_negation


df <- data.frame(exp1 = mca.spleen@assays$RNA@data["Cd74",],
                 exp2 = mca.spleen@assays$RNA@data["Igkc",],
                 id = as.character(mca.spleen@active.ident))
df$id <- ifelse(df$id == "Marginal zone B cell(Spleen)", "Marginal zone B cell(Spleen)", "Other")

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))

df <- data.frame(exp1 = mca.spleen@assays$RNA@data["Tmsb4x",],
                 exp2 = mca.spleen@assays$RNA@data["Cd79a",],
                 id = as.character(mca.spleen@active.ident))

df$id <- ifelse(df$id == "Marginal zone B cell(Spleen)", "Marginal zone B cell(Spleen)", "Other")

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))


dist(t(df.id[1:15, 1:15]))
dist.id <- melt(as.matrix(dist(t(df.id))))
dist.id <- dist.id[dist.id$value != 0, ]
dist.id[order(dist.id$value, decreasing = F),]

as.matrix(as.matrix(dist(t(df.id[1:50, 1:50]))))["Ighm", "Igkc"]
as.matrix(as.matrix(dist(t(df.other[1:50, 1:50]))))["Ighm", "Igkc"]

dist(t(df.id[1:15, 1:15]))
dist(t(df.other[1:15, 1:15]))
dist.c <- melt(as.matrix(((dist(t(df.other)) + 1) / (dist(t(df.id)) + 1))))
dist.c <- dist.c[dist.c$value != 0, ]
dist.c[order(dist.c$value, decreasing = T), ]

dist.o <- melt(as.matrix(dist(t(df.other))))
dist.o <- dist.id[dist.o$value != 0, ]
dist.o[order(dist.o$value, decreasing = T),]
dist.o[order(dist.o$Var1, dist.o$Var2),]
dist.id[order(dist.id$Var1, dist.id$Var2),]


max(expr.matrix.1[19,], na.rm=TRUE)
apply(expr.matrix.1, 2, max)
mca.spleen <- FindVariableFeatures(mca.spleen)
mca.spleen@assays$RNA@var.features

marker_stepbystep(mca.spleen, cellgroup = "Marginal zone B cell(Spleen)", step = 0.1)

as.matrix(dist(t(df.id[1:15, 1:15])))
```

```{r}
df <- data.frame(exp1 = normalize(mca.spleen@assays$RNA@data["Cd74",]),
                 exp2 = normalize(mca.spleen@assays$RNA@data["Igkc",]),
                 id = as.character(mca.spleen@active.ident))
df$id <- ifelse(df$id == "Marginal zone B cell(Spleen)", "Marginal zone B cell(Spleen)", "Other")
df$exp3 <- (df$exp1 + 0.01)*(df$exp2 + 0.01)
df.i <- df[df$id == "Marginal zone B cell(Spleen)", ]
df.o <- df[df$id == "Other", ]
df.i <- df.i[order(df.i$exp3, decreasing = T), ]
df.o <- df.o[order(df.o$exp3, decreasing = T), ]
df.a <- data.frame(id = df.i$exp3,
                   other = df.o[1:nrow(df.i),]$exp3)

df.a <- rbind(df.i, df.o[1:nrow(df.i),])

ggplot(df.a) +
  geom_point(aes(exp1, exp2, col = id))

# dist(as.matrix(t(df.a)))

df <- data.frame(exp1 = normalize(mca.spleen@assays$RNA@data["Tmsb4x",]),
                 exp2 = normalize(mca.spleen@assays$RNA@data["Cd79a",]),
                 id = as.character(mca.spleen@active.ident))
df$id <- ifelse(df$id == "Marginal zone B cell(Spleen)", "Marginal zone B cell(Spleen)", "Other")
df$exp3 <- (df$exp1 + 0.01)*(df$exp2 + 0.01)
df.i <- df[df$id == "Marginal zone B cell(Spleen)", ]
df.o <- df[df$id == "Other", ]
df.i <- df.i[order(df.i$exp3, decreasing = T), ]
df.o <- df.o[order(df.o$exp3, decreasing = T), ]
df.a <- data.frame(id = df.i$exp3,
                   other = df.o[1:nrow(df.i),]$exp3)

df.a <- rbind(df.i, df.o[1:nrow(df.i),])

ggplot(df.a) +
  geom_point(aes(exp1, exp2, col = id))

# dist(as.matrix(t(df.a)))


get_split_pos_c.2(mca.spleen, "Cd74",	"Igkc", "Marginal zone B cell(Spleen)", step = 0.1)
get_split_pos_c.2(mca.spleen, "Cd74",	"Igkc", "Marginal zone B cell(Spleen)", step = 0.1)
get_split_pos.2(mca.spleen, "Cd74", "Marginal zone B cell(Spleen)", step = 0.1)
get_split_pos.2(mca.spleen, "Cd22", "Marginal zone B cell(Spleen)", step = 0.1)
get_split_pos_c.2(mca.spleen, "Tmsb4x",	"Cd79a", "Marginal zone B cell(Spleen)", step = 0.1)


get_split_pos_pos(mca.spleen, "Cd74",	"Igkc", "Marginal zone B cell(Spleen)", step = 0.1)
get_split_pos_neg(mca.spleen, "Cd74",	"S100a4", "Marginal zone B cell(Spleen)", step = 0.1)
get_split_pos_neg(mca.spleen, "Cd74",	"Cd7", "Marginal zone B cell(Spleen)", step = 0.1)
get_split_neg_neg(mca.spleen, "S100a4",	"Cd7", "Marginal zone B cell(Spleen)", step = 0.1)
re1 <- get_split_neg_neg(mca.spleen, "S100a4",	"Plbd1", "Marginal zone B cell(Spleen)", step = 0.1)
re1
```

```{r}
get_split_pos_neg <- function(scrna, gene1, gene2, id, step = 0.01) {
  data.mat.surf <- data.frame(exp1 = normalize(scrna@assays$RNA@data[gene1,]),
                              exp2 = normalize(scrna@assays$RNA@data[gene2,]),
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  data.id.l <- nrow(data.id)
  data.o.l <- nrow(data.other)
  data.all.l <- nrow(data.mat.surf)

  x.max <- 0
  x.min <- 1
  x.num <- 1/step

  x.size.factor <- 10*(length(data.id$exp1)/length(data.other$exp1))

  for (x.val in seq(0, 1, step)) {
    for (y.val in seq(0, 1, step)) {
      data.i.a <- data.id[data.id$exp1 > x.val & data.id$exp2 < y.val, ]
      tp <- nrow(data.i.a)
      data.o.a <- data.other[data.other$exp1 > x.val & data.other$exp2 < y.val, ]
      fp <- nrow(data.o.a)
      data.i.b <- data.id[data.id$exp1 <= x.val | data.id$exp2 >= y.val, ]
      fn <- nrow(data.i.b)
      data.o.b <- data.other[data.other$exp1 <= x.val | data.other$exp2 >= y.val, ]
      tn <- nrow(data.o.b)
  
      x.margin.a <- sum((data.i.a$exp1 - x.val))*nrow(data.o.b) + sum((y.val - data.i.a$exp2))*nrow(data.o.b) +
        sum((x.val -data.o.b$exp1))*nrow(data.i.a) + sum((data.o.b$exp2 - y.val))*nrow(data.i.a) -
        sum((data.o.a$exp1 - x.val))*nrow(data.o.b) - sum((y.val - data.o.a$exp2))*nrow(data.o.b)
      x.margin <- tp - fp
      x.margin <- x.margin/data.all.l
      x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*x.margin.a
      de <- data.frame(gene1, gene2, x.val, y.val, x.margin)
      gene.prauc <- rbind(gene.prauc, de)
    }
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  x.val <- x.split[,3]
  y.val <- x.split[,4]
  x.margin <- x.split[,5]
  data.i.a <- data.id[data.id$exp1 > x.val & data.id$exp2 < y.val, ]
  tp <- nrow(data.i.a)
  data.o.a <- data.other[data.other$exp1 > x.val & data.other$exp2 < y.val, ]
  fp <- nrow(data.o.a)
  data.i.b <- data.id[data.id$exp1 <= x.val | data.id$exp2 >= y.val, ]
  fn <- nrow(data.i.b)
  data.o.b <- data.other[data.other$exp1 <= x.val | data.other$exp2 >= y.val, ]
  tn <- nrow(data.o.b)
  
  x.margin.a <- sum((data.i.a$exp1 - x.val))*nrow(data.o.b) + sum((y.val - data.i.a$exp2))*nrow(data.o.b) +
        sum((x.val -data.o.b$exp1))*nrow(data.i.a) + sum((data.o.b$exp2 - y.val))*nrow(data.i.a) -
        sum((data.o.a$exp1 - x.val))*nrow(data.o.b) - sum((y.val - data.o.a$exp2))*nrow(data.o.b)

  x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*x.margin.a
  
  x.split <- data.frame(gene1, gene2, x.val, y.val, x.margin, x.margin.adj, tp, fp, "+", "-")
  return(x.split)
}


get_split_neg_neg <- function(scrna, gene1, gene2, id, step = 0.01) {
  data.mat.surf <- data.frame(exp1 = normalize(scrna@assays$RNA@data[gene1,]),
                              exp2 = normalize(scrna@assays$RNA@data[gene2,]),
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  data.id.l <- nrow(data.id)
  data.o.l <- nrow(data.other)
  data.all.l <- nrow(data.mat.surf)

  x.max <- 0
  x.min <- 1
  x.num <- 1/step
  # x.size.factor <- 10*(length(data.id$exp1)/length(data.other$exp1))

  for (x.val in seq(0, 1, step)) {
    for (y.val in seq(0, 1, step)) {
      data.i.a <- data.id[data.id$exp1 < x.val & data.id$exp2 < y.val, ]
      tp <- nrow(data.i.a)
      data.o.a <- data.other[data.other$exp1 < x.val & data.other$exp2 < y.val, ]
      fp <- nrow(data.o.a)
      data.i.b <- data.id[data.id$exp1 >= x.val | data.id$exp2 >= y.val, ]
      fn <- nrow(data.i.b)
      data.o.b <- data.other[data.other$exp1 >= x.val | data.other$exp2 >= y.val, ]
      tn <- nrow(data.o.b)
      
      x.margin <- tp - fp
      x.margin <- x.margin/data.all.l
  
      de <- data.frame(gene1, gene2, x.val, y.val, x.margin)
      gene.prauc <- rbind(gene.prauc, de)
    }
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  x.val <- x.split[,3]
  y.val <- x.split[,4]
  x.margin <- x.split[,5]
  data.i.a <- data.id[data.id$exp1 < x.val & data.id$exp2 < y.val, ]
  tp <- nrow(data.i.a)
  data.o.a <- data.other[data.other$exp1 < x.val & data.other$exp2 < y.val, ]
  fp <- nrow(data.o.a)
  data.i.b <- data.id[data.id$exp1 >= x.val | data.id$exp2 >= y.val, ]
  fn <- nrow(data.i.b)
  data.o.b <- data.other[data.other$exp1 >= x.val | data.other$exp2 >= y.val, ]
  tn <- nrow(data.o.b)
  
  x.margin.a <- sum((data.i.a$exp1 - x.val))*nrow(data.o.b) + sum((data.i.a$exp2 - y.val))*nrow(data.o.b) +
    sum((x.val -data.o.b$exp1))*nrow(data.i.a) + sum((y.val -data.o.b$exp2))*nrow(data.i.a) -
    sum((data.o.a$exp1 - x.val))*nrow(data.o.b) - sum((data.o.a$exp2 - y.val))*nrow(data.o.b)
      
  x.margin.a <- -x.margin.a
  x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*x.margin.a
  
  x.split <- data.frame(gene1, gene2, x.val, y.val, x.margin, x.margin.adj, tp, fp, "-", "-")
  return(x.split)
}

get_split_pos_pos <- function(scrna, gene1, gene2, id, step = 0.01) {
  data.mat.surf <- data.frame(exp1 = normalize(scrna@assays$RNA@data[gene1,]),
                              exp2 = normalize(scrna@assays$RNA@data[gene2,]),
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  data.id.l <- nrow(data.id)
  data.o.l <- nrow(data.other)
  data.all.l <- nrow(data.mat.surf)

  x.max <- 0
  x.min <- 1
  x.num <- 1/step

  x.size.factor <- 10*(length(data.id$exp1)/length(data.other$exp1))

  for (x.val in seq(0, 1, step)) {
    for (y.val in seq(0, 1, step)) {
      data.i.a <- data.id[data.id$exp1 > x.val & data.id$exp2 > y.val, ]
      tp <- nrow(data.i.a)
      data.o.a <- data.other[data.other$exp1 > x.val & data.other$exp2 > y.val, ]
      fp <- nrow(data.o.a)
      data.i.b <- data.id[data.id$exp1 <= x.val | data.id$exp2 <= y.val, ]
      fn <- nrow(data.i.b)
      data.o.b <- data.other[data.other$exp1 <= x.val | data.other$exp2 <= y.val, ]
      tn <- nrow(data.o.b)
  
      # x.margin.a <- sum((data.i.a$exp1 - x.val))*nrow(data.o.b) + sum((data.i.a$exp2 - y.val))*nrow(data.o.b) +
      #   sum((x.val -data.o.b$exp1))*nrow(data.i.a) + sum((y.val -data.o.b$exp2))*nrow(data.i.a) -
      #   sum((data.o.a$exp1 - x.val))*nrow(data.o.b) - sum((data.o.a$exp2 - y.val))*nrow(data.o.b)
      x.margin <- tp - fp
      x.margin <- x.margin/data.all.l
  
      # x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*x.margin.a#*((x1.factor*x2.factor)**2)
  
      # de <- data.frame(gene1, gene2, x.val, y.val, x.margin, x.margin.adj, tp, fp, "+", "+")
      de <- data.frame(gene1, gene2, x.val, y.val, x.margin)
      gene.prauc <- rbind(gene.prauc, de)
    }
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  x.val <- x.split[,3]
  y.val <- x.split[,4]
  x.margin <- x.split[,5]
  data.i.a <- data.id[data.id$exp1 > x.val & data.id$exp2 > y.val, ]
  tp <- nrow(data.i.a)
  data.o.a <- data.other[data.other$exp1 > x.val & data.other$exp2 > y.val, ]
  fp <- nrow(data.o.a)
  data.i.b <- data.id[data.id$exp1 <= x.val | data.id$exp2 <= y.val, ]
  fn <- nrow(data.i.b)
  data.o.b <- data.other[data.other$exp1 <= x.val | data.other$exp2 <= y.val, ]
  tn <- nrow(data.o.b)
  
  x.margin.a <- sum((data.i.a$exp1 - x.val))*nrow(data.o.b) + sum((data.i.a$exp2 - y.val))*nrow(data.o.b) +
    sum((x.val -data.o.b$exp1))*nrow(data.i.a) + sum((y.val -data.o.b$exp2))*nrow(data.i.a) -
    sum((data.o.a$exp1 - x.val))*nrow(data.o.b) - sum((data.o.a$exp2 - y.val))*nrow(data.o.b)
  x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*x.margin.a#*((x1.factor*x2.factor)**2)
  x.split <- data.frame(gene1, gene2, x.val, y.val, x.margin, x.margin.adj, tp, fp, "+", "+")
  return(x.split)
}
```




```{r}
get_split_pos.1 <- function(scrna, gene, id, step = 0.01) {
  data.mat.surf <- data.frame(exp = scrna@assays$RNA@data[gene,],
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]

  x.max <- max(data.id$exp)
  x.min <- min(data.id$exp)
  x.num <- 1/step

  x.factor <- (mean(data.id$exp) + 0.001)/(mean(data.other$exp) + 0.001)

  x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(x.min, x.max, (x.max - x.min)/x.num)) {
    tp <- sum(data.id$exp > x.val)
    fp <- sum(data.other$exp > x.val)
    tn <- sum(data.other$exp <= x.val)
    fn <- sum(data.id$exp <= x.val)

    x.margin <- tp - fp#*x.size.factor
    # x.margin <- tp - fp*x.size.factor
    # x.margin <- (x.factor**2)*x.margin

    # x.margin.adj <- x.margin*x.factor
    x.margin.adj <- x.margin*(tp/length(data.id$exp))*(tn/length(data.other$exp))*(x.factor**2)

    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "+")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene)
  return(x.split)
}

get_split_pos_pos <- function(scrna, gene1, gene2, id, step = 0.01) {
  data.mat.surf <- data.frame(exp1 = normalize(scrna@assays$RNA@data[gene1,]),
                              exp2 = normalize(scrna@assays$RNA@data[gene2,]),
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  data.id.l <- nrow(data.id)
  data.o.l <- nrow(data.other)
  data.all.l <- nrow(data.mat.surf)

  x.max <- 0
  x.min <- 1
  x.num <- 1/step

  x.size.factor <- 10*(length(data.id$exp1)/length(data.other$exp1))

  for (x.val in seq(0, 1, step)) {
    for (y.val in seq(0, 1, step)) {
      data.i.a <- data.id[data.id$exp1 > x.val & data.id$exp2 > y.val, ]
      tp <- nrow(data.i.a)
      data.o.a <- data.other[data.other$exp1 > x.val & data.other$exp2 > y.val, ]
      fp <- nrow(data.o.a)
      data.i.b <- data.id[data.id$exp1 <= x.val | data.id$exp2 <= y.val, ]
      fn <- nrow(data.i.b)
      data.o.b <- data.other[data.other$exp1 <= x.val | data.other$exp2 <= y.val, ]
      tn <- nrow(data.o.b)
  
      # x.margin.a <- sum((data.i.a$exp1 - x.val))*nrow(data.o.b) + sum((data.i.a$exp2 - y.val))*nrow(data.o.b) +
      #   sum((x.val -data.o.b$exp1))*nrow(data.i.a) + sum((y.val -data.o.b$exp2))*nrow(data.i.a) -
      #   sum((data.o.a$exp1 - x.val))*nrow(data.o.b) - sum((data.o.a$exp2 - y.val))*nrow(data.o.b)
      x.margin <- tp - fp
      x.margin <- x.margin/data.all.l
  
      # x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*x.margin.a#*((x1.factor*x2.factor)**2)
  
      # de <- data.frame(gene1, gene2, x.val, y.val, x.margin, x.margin.adj, tp, fp, "+", "+")
      de <- data.frame(gene1, gene2, x.val, y.val, x.margin)
      gene.prauc <- rbind(gene.prauc, de)
    }
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  x.val <- x.split[,3]
  y.val <- x.split[,4]
  x.margin <- x.split[,5]
  data.i.a <- data.id[data.id$exp1 > x.val & data.id$exp2 > y.val, ]
  tp <- nrow(data.i.a)
  data.o.a <- data.other[data.other$exp1 > x.val & data.other$exp2 > y.val, ]
  fp <- nrow(data.o.a)
  data.i.b <- data.id[data.id$exp1 <= x.val | data.id$exp2 <= y.val, ]
  fn <- nrow(data.i.b)
  data.o.b <- data.other[data.other$exp1 <= x.val | data.other$exp2 <= y.val, ]
  tn <- nrow(data.o.b)
  
  x.margin.a <- sum((data.i.a$exp1 - x.val))*nrow(data.o.b) + sum((data.i.a$exp2 - y.val))*nrow(data.o.b) +
    sum((x.val -data.o.b$exp1))*nrow(data.i.a) + sum((y.val -data.o.b$exp2))*nrow(data.i.a) -
    sum((data.o.a$exp1 - x.val))*nrow(data.o.b) - sum((data.o.a$exp2 - y.val))*nrow(data.o.b)
  x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*x.margin.a#*((x1.factor*x2.factor)**2)
  x.split <- data.frame(gene1, gene2, x.val, y.val, x.margin, x.margin.adj, tp, fp, "+", "+")
  return(x.split)
}

get_split_pos_c.3 <- function(scrna, gene1, gene2, id, step = 0.01) {
  data.mat.surf <- data.frame(exp1 = normalize(scrna@assays$RNA@data[gene1,]),
                              exp2 = normalize(scrna@assays$RNA@data[gene2,]),
                              id = as.character(scrna@active.ident))
  data.mat.surf$exp <- (data.mat.surf$exp1 + 0.01)*(data.mat.surf$exp2 + 0.01)
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  data.id.l <- nrow(data.id)
  data.o.l <- nrow(data.other)
  data.all.l <- nrow(data.mat.surf)

  x.max <- 0
  x.min <- 1
  x.num <- 1/step

  x.factor <- (mean(data.id$exp) + 0.001)/(mean(data.other$exp) + 0.001)

  x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(0, 1, step)) {
    # tp <- sum(data.id$exp > x.val)
    # fp <- sum(data.other$exp > x.val)
    # tn <- sum(data.other$exp <= x.val)
    # fn <- sum(data.id$exp <= x.val)
    data.i.a <- data.id[data.id$exp > x.val, ]
    tp <- nrow(data.i.a)
    data.o.a <- data.other[data.other$exp > x.val, ]
    fp <- nrow(data.o.a)
    data.i.b <- data.id[data.id$exp <= x.val, ]
    fn <- nrow(data.i.b)
    data.o.b <- data.other[data.other$exp <= x.val, ]
    tn <- nrow(data.o.b)

    # x.margin <- sum((data.i.a$exp - x.val))*nrow(data.o.b) +
    #   sum((x.val -data.o.b$exp))*nrow(data.i.a) -
    #   sum((data.o.a$exp - x.val))*nrow(data.o.b)
    x.margin <- tp - fp
    x.margin <- x.margin/data.all.l

    x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*(x.factor**2)

    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "+")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene1, gene2)
  return(x.split)
}



get_split_pos.2 <- function(scrna, gene, id, step = 0.01) {
  data.mat.surf <- data.frame(exp = normalize(scrna@assays$RNA@data[gene,]),
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  data.id.l <- nrow(data.id)
  data.o.l <- nrow(data.other)
  data.all.l <- nrow(data.mat.surf)

  x.max <- 0
  x.min <- 1
  x.num <- 1/step

  x.factor <- (mean(data.id$exp) + 0.001)/(mean(data.other$exp) + 0.001)

  x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(0, 1, step)) {
    tp <- sum(data.id$exp > x.val)
    fp <- sum(data.other$exp > x.val)
    tn <- sum(data.other$exp <= x.val)
    fn <- sum(data.id$exp <= x.val)
    data.i.a <- data.id[data.id$exp > x.val, ]
    data.o.a <- data.other[data.other$exp > x.val, ]
    data.i.b <- data.id[data.id$exp <= x.val, ]
    data.o.b <- data.other[data.other$exp <= x.val, ]

    x.margin <- sum((data.i.a$exp - x.val))*nrow(data.o.b) +
      sum((x.val -data.o.b$exp))*nrow(data.i.a) -
      sum((data.o.a$exp - x.val))*nrow(data.o.b)
    x.margin <- x.margin/data.all.l

    # x.margin <- sum((data.id[data.id$exp > x.val, ]$exp - x.val))*length(data.other[data.other$exp <x.val, ]$id) +
    #   sum((x.val - data.other[data.other$exp <x.val, ]$exp))*length(data.id[data.id$exp > x.val, ]$id) -
    #   sum((data.other[data.other$exp > x.val, ]$exp - x.val))*length(data.other[data.other$exp <x.val, ]$id)

    x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*(x.factor**2)

    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "+")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene)
  return(x.split)
}

get_split_pos.1 <- function(scrna, gene, id, step = 0.01) {
  data.mat.surf <- data.frame(exp = scrna@assays$RNA@data[gene,],
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]

  x.max <- max(data.id$exp)
  x.min <- min(data.id$exp)
  x.num <- 1/step

  # x.factor <- (mean(data.id$exp) + 0.001)/(mean(data.other$exp) + 0.001)

  x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(x.min, x.max, (x.max - x.min)/x.num)) {
    tp <- sum(data.id$exp > x.val)
    fp <- sum(data.other$exp > x.val)
    tn <- sum(data.other$exp <= x.val)
    fn <- sum(data.id$exp <= x.val)

    x.margin <- tp - fp#*x.size.factor
    # x.margin <- tp - fp*x.size.factor
    # x.margin <- (x.factor**2)*x.margin

    # x.margin.adj <- x.margin*x.factor
    x.margin.adj <- x.margin*(tp/length(data.id$exp))*(tn/length(data.other$exp))*(x.factor**2)

    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "+")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene)
  return(x.split)
}
```


```{r}
scrna <- mca.spleen
gene <- "Cd19"
id <- "Marginal zone B cell(Spleen)"
step <- 0.1
x.val <- 1.213446

get_split_pos.3 <- function(scrna, gene, id, step = 0.01) {
  data.mat.surf <- data.frame(exp = scrna@assays$RNA@data[gene,],
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]

  x.max <- max(data.id$exp)
  x.min <- min(data.id$exp)
  x.num <- 1/step

  # x.factor <- (mean(data.id$exp) + 0.0001)/(mean(data.other$exp) + 0.0001)

  # x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(x.min, x.max, (x.max - x.min)/x.num)) {
    tp <- sum(data.id$exp > x.val)
    fp <- sum(data.other$exp > x.val)
    tn <- sum(data.other$exp <= x.val)
    fn <- sum(data.id$exp <= x.val)

    x.margin <- tp - fp#*x.size.factor
    # x.margin <- tp - fp*x.size.factor
    # x.margin <- (x.factor**2)*x.margin
    x.factor <- (tp/nrow(data.id) + 0.0001)/(fp/nrow(data.other) + 0.0001)
    # data.mat.surf[data.mat.surf$exp <= x.val, ]$exp <- 0
    # data.mat.surf[data.mat.surf$exp > x.val, ]$exp <- 1
    # 
    # data.id <- data.mat.surf[data.mat.surf$id == id,]
    # data.other <- data.mat.surf[data.mat.surf$id != id,]
    
    # x.factor <- (mean(data.id$exp) + 0.001)/(mean(data.other$exp) + 0.001)
    # x.margin.adj <- x.margin*x.factor
    x.margin.adj <- x.margin*(tp/length(data.id$exp))*(tn/length(data.other$exp))*(x.factor**2)

    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "+")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene)
  return(x.split)
}

normalize <- function(x, ...) {
    return((x - min(x, ...)) /(max(x, ...) - min(x, ...)))
}

normalize(a)

tp + fp
log2(4.394653)

get_split_pos.1(mca.spleen, "Cd19", "Marginal zone B cell(Spleen)")
```




```{r}
mca.spleen <- FindVariableFeatures(mca.spleen)
mca.spleen <- ScaleData(mca.spleen)
mca.spleen <- RunPCA(mca.spleen, npcs = 100, ndims.print = 1:5, nfeatures.print = 5)
```




# Get single markers from Seurat and PRAUC

```{r warning=F}
matrix_cometsc <- Seurat::GetAssayData(mca.spleen) #gets the normalized count matrix
write.table(as.matrix(matrix_cometsc), file= "exprs.txt", row.names=TRUE, col.names=TRUE, sep = "\t", quote = FALSE)


umap_cometsc <- Embeddings(mca.spleen, reduction = "pca")
umap_cometsc <- umap_cometsc[,c(1,2)]
write.table(umap_cometsc, file="mca.spleen.vis.txt", row.names=TRUE, col.names=FALSE, sep = "\t", quote = FALSE)

umap_cometsc <- Embeddings(so, reduction = "umap")
write.table(umap_cometsc, file="mca.spleen.vis.txt", row.names=TRUE, col.names=FALSE, sep = "\t", quote = FALSE)

Idents(mca.spleen) <- "anno"

mca.spleen@meta.data$anno.n <- as.numeric(Idents(mca.spleen))

Idents(mca.spleen) <- "anno.n"

cluster_cometsc <- noquote(as.matrix((Idents(mca.spleen)))) # Get the active cluster identities. Should be numbers. COMET does not take Non-Number cluster names.

write.table(cluster_cometsc, file = "mca.spleen.clusters.txt", row.names=TRUE, col.names=FALSE, sep = "\t", quote = FALSE)


write.table(rownames(mca.spleen), file = "mca.spleen.genes.txt", col.names = F, row.names = F, quote = F)


matrix_cometsc <- Seurat::GetAssayData(mca.spleen) #gets the normalized count matrix

write.table(as.matrix(matrix_cometsc), file= "exprs.txt", row.names=TRUE, col.names=TRUE, sep = "\t", quote = FALSE)

```

```{r}
get_split_pos.1(cbmc, "IGHD", "6")
```
```{r}
VlnPlot(cbmc, "IGHD")
```


```{r}
GetAssays(assays, index)
```


```{r}

get_split_pos.1 <- function(scrna, gene, id, step = 0.01) {
  data.mat.surf <- data.frame(exp = scrna@assays$RNA@data[gene,],
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]

  x.max <- max(data.id$exp)
  x.min <- min(data.id$exp)
  x.num <- 1/step
  
  x.factor <- (mean(data.id$exp) + 0.001)/(mean(data.other$exp) + 0.001)
  
  x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(x.min, x.max, (x.max - x.min)/x.num)) {
    tp <- sum(data.id$exp > x.val)
    fp <- sum(data.other$exp > x.val)
    tn <- sum(data.other$exp <= x.val)
    fn <- sum(data.id$exp <= x.val)
    
    x.margin <- tp - fp#*x.size.factor
    # x.margin <- tp - fp*x.size.factor
    # x.margin <- (x.factor**2)*x.margin
    
    # x.margin.adj <- x.margin*x.factor
    x.margin.adj <- x.margin*(tp/length(data.id$exp))*(tn/length(data.other$exp))*(x.factor**2)
    
    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "+")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene)
  return(x.split)
}


get_split_neg.1 <- function(scrna, gene, id, step = 0.01) {
  data.mat.surf <- data.frame(exp = scrna@assays$RNA@data[gene,],
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]

  x.max <- max(data.id$exp)
  x.min <- min(data.id$exp)
  x.num <- 1/step
  
  x.factor <- (mean(data.other$exp) + 0.001)/(mean(data.id$exp) + 0.001)
  
  x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(x.min, x.max, (x.max - x.min)/x.num)) {
    tp <- sum(data.id$exp < x.val)
    fp <- sum(data.other$exp < x.val)
    tn <- sum(data.other$exp >= x.val)
    fn <- sum(data.id$exp >= x.val)
    
    x.margin <- tp - fp#*x.size.factor
    # x.margin <- tp - fp*x.size.factor
    # x.margin <- (x.factor**2)*x.margin
    
    # x.margin.adj <- x.margin*x.factor
    x.margin.adj <- x.margin*(tp/length(data.id$exp))*(tn/length(data.other$exp))*(x.factor**2)
    
    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "-")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene)
  return(x.split)
}
```





Compare top 9 marker from DE and prauc based method

# Plot PRAUC of TOP 9 Positive markers from DE and prauc based ranking

```{r}
Idents(cbmc) <- "seurat_clusters"

for (x.cluster in seq(1,8)) {
  df.prauc <- markers.prauc[[x.cluster]]
  df.wilcox <- markers.wilcox[[x.cluster]]
  
  g <- ggplot()
  for (genes in intersect(rownames(df.wilcox)[1:9], df.prauc$gene[1:9])) {
    df <- get_gene_PRAUC_matrix(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("Seurat and PRAUC")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  for (genes in setdiff(rownames(df.wilcox)[1:9], df.prauc$gene[1:9])) {
    df <- get_gene_PRAUC_matrix(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("Seurat")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  for (genes in setdiff(df.prauc$gene[1:9], rownames(df.wilcox)[1:9])) {
    if (df.prauc[df.prauc$gene == genes, ]$direction == "+") {
      df <- get_gene_PRAUC_matrix(cbmc, genes, x.cluster, step = 0.01)
      df$gene = as.factor(genes)
      df$method = as.factor("PRAUC")
      g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
    }else{
      df <- get_gene_PRAUC_matrix_neg(cbmc, genes, x.cluster, step = 0.01)
      df$gene = as.factor(genes)
      df$method = as.factor("PRAUC")
      g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
    }
  }
  print(g)
}

```


# Plot PRAUC of TOP 12 markers from COMET and prauc ranking

```{r fig.height=6, fig.width=8}
Idents(cbmc) <- "seurat_clusters"
x.cluster <- 12
for (x.cluster in seq(1,8)) {
  genes <- read.csv(paste("/home/ronghui/project/dbmaker/data/cluster_", x.cluster, "_singleton_all_ranked.csv", sep = ""))
  genes <- genes[1:10, ]
  comet.genes.pos <- genes[genes$Log2FoldChange > 0, ]$gene_1
  comet.genes.neg <- genes[genes$Log2FoldChange < 0, ]$gene_1
  comet.genes.neg <-gsub("_negation", "", comet.genes.neg)
  
  df.prauc <- markers.prauc[[x.cluster]]
  df.prauc <- df.prauc[1:10,]
  df.prauc.pos <- df.prauc[df.prauc$direction == "+", ]$gene
  df.prauc.neg <- df.prauc[df.prauc$direction == "-", ]$gene
  
  g <- ggplot()
  for (genes in intersect(comet.genes.pos, df.prauc.pos)) {
    df <- get_gene_PRAUC_matrix(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("Seurat and COMET")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  for (genes in setdiff(comet.genes.pos, df.prauc.pos)) {
    df <- get_gene_PRAUC_matrix(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("COMET")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  for (genes in setdiff(df.prauc.pos, comet.genes.pos)) {
    df <- get_gene_PRAUC_matrix(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("PRAUC")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  
  for (genes in intersect(comet.genes.neg, df.prauc.neg)) {
    df <- get_gene_PRAUC_matrix_neg(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("Seurat and COMET")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  for (genes in setdiff(comet.genes.neg, df.prauc.neg)) {
    df <- get_gene_PRAUC_matrix_neg(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("COMET")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  for (genes in setdiff(df.prauc.neg, comet.genes.neg)) {
    df <- get_gene_PRAUC_matrix_neg(cbmc, genes, x.cluster, step = 0.01)
    df$gene = as.factor(genes)
    df$method = as.factor("PRAUC")
    g <- g + geom_line(df, mapping = aes(x.rec, x.pre, color = method))
  }
  print(g + xlab("Recall") + ylab("Precision") + ggtitle(paste(x.cluster)))
}

cbmc <- makeid(cbmc, "6")
VlnPlot(cbmc, comet.genes.pos)
VlnPlot(cbmc, df.prauc.pos)
genes[genes$gene_1 == "CD11c", ]
df.prauc[df.prauc$gene== "CD11c",]
genes <- read.csv(paste("/home/ronghui/project/dbmaker/data/cluster_", "12", "_singleton_all_ranked.csv", sep = ""))
genes
markers.prauc[[6]]
genes$hgrank + genes$fcrank
markers.i
cbmc <- makeid(cbmc, "12")
DefaultAssay(cbmc) <- "RNA"
VlnPlot(cbmc, "PROM1")
VlnPlot(cbmc, "CD34")
VlnPlot(cbmc, "SPINK2")

```

```{r fig.height=6, fig.width=8}
Idents(cbmc) <- "seurat_clusters"
cbmc <- makeid(cbmc, "6")
DefaultAssay(cbmc) <- "RNA"
VlnPlot(cbmc, "CD19")
DefaultAssay(cbmc) <- "RNA"
VlnPlot(cbmc, "HLA-DOB")
VlnPlot(cbmc, df.prauc.pos)


id <- "6"
gene <- "CD19"

get_split_pos.2 <- function(scrna, gene, id, step = 0.01) {
  data.mat.surf <- data.frame(exp = scrna@assays$RNA@data[gene,],
                              id = as.character(scrna@active.ident))
  gene.prauc <- data.frame(x.val <- c(),
                           margin <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  data.id.l <- nrow(data.id)
  data.o.l <- nrow(data.other)
  data.all.l <- nrow(data.mat.surf)

  x.max <- max(data.id$exp)
  x.min <- min(data.id$exp)
  x.num <- 1/step
  
  x.factor <- (mean(data.id$exp) + 0.001)/(mean(data.other$exp) + 0.001)
  
  x.size.factor <- 10*(length(data.id$exp)/length(data.other$exp))

  for (x.val in seq(x.min, x.max, (x.max - x.min)/x.num)) {
    tp <- sum(data.id$exp > x.val)
    fp <- sum(data.other$exp > x.val)
    tn <- sum(data.other$exp <= x.val)
    fn <- sum(data.id$exp <= x.val)
    data.i.a <- data.id[data.id$exp > x.val, ]
    data.o.a <- data.other[data.other$exp > x.val, ]
    data.i.b <- data.id[data.id$exp <= x.val, ]
    data.o.b <- data.other[data.other$exp <= x.val, ]
    
    x.margin <- sum((data.i.a$exp - x.val))*nrow(data.o.b) + 
      sum((x.val -data.o.b$exp))*nrow(data.i.a) -
      sum((data.o.a$exp - x.val))*nrow(data.o.b)
    x.margin <- x.margin/data.all.l
    
    # x.margin <- sum((data.id[data.id$exp > x.val, ]$exp - x.val))*length(data.other[data.other$exp <x.val, ]$id) + 
    #   sum((x.val - data.other[data.other$exp <x.val, ]$exp))*length(data.id[data.id$exp > x.val, ]$id) -
    #   sum((data.other[data.other$exp > x.val, ]$exp - x.val))*length(data.other[data.other$exp <x.val, ]$id)

    x.margin.adj <- x.margin*(tp/data.id.l)*(tn/data.o.l)*(x.factor**2)
    
    de <- data.frame(x.val, x.margin, x.margin.adj, tp, fp, "+")
    gene.prauc <- rbind(gene.prauc, de)
  }
  gene.prauc <- gene.prauc[order(gene.prauc$x.margin, decreasing = T),]
  x.split <- gene.prauc[1,]
  rownames(x.split) <- paste(gene)
  return(x.split)
}

x.val <- 0.7016315
Idents(cbmc) <- "seurat_clusters"
cbmc <- makeid(cbmc, "6")
DefaultAssay(cbmc) <- "RNA"
VlnPlot(cbmc, "CD19")
VlnPlot(cbmc, "HLA-DOB")
get_split_pos.2(cbmc, "CD19", "6")
get_split_pos.1(cbmc, "CD19", "6")
get_split_pos.1(cbmc, "HLA-DOB", "6")
get_split_pos.1(cbmc, "CD79B", "6")

df <- data.frame()
for (gene in markers.prauc[[6]]$gene[1:20]) {
  df.s <- get_split_pos.2(cbmc, gene, "6")
  df <- rbind(df, df.s)
}
df[order(df$x.margin.adj, decreasing = T), ]

markers.wilcox[[6]]

Idents(cbmc) <- "seurat_clusters"
markers.wilcox.6 <- FindMarkers(cbmc, ident.1 = "12", test.use = "LR")
markers.wilcox.6["CD19",]
markers.wilcox.6["HLA-DOB",]

cbmc <- makeid(cbmc, "6")
VlnPlot(cbmc, "VPREB3")
VlnPlot(cbmc, "CD19")

markers.i

get_split_pos.2(cbmc, "CD34", "12")
get_split_pos.2(cbmc, "CRHBP", "12")
get_split_pos.1(cbmc, "SPINK2", "12")
get_split_pos.2(cbmc, "SPINK2", "12")

```


# Detect combine markers for interested cell groups

```{r}
# makers.prauc <- list()
# for (x.cluster in seq(1,8)) {
#   df.split <- Detect_combine_markers(cbmc, x.cluster, markers.allset, max.gene = 50)
#   makers.prauc[[x.cluster]] <- df.split
# }

load(file = "first8clusters.combine.markers.rds")

makers.prauc

id <- "6"
df <- data.frame(exp1 = normalize(cbmc@assays$RNA@data["FCRLA",]),
                 exp2 = normalize(cbmc@assays$RNA@data["HLA-DRA",]),
                 id = as.character(cbmc@active.ident))


df.i <- df[df$id == id, ]
df.o <- df[df$id != id, ]

dist(rbind(df.i$exp1, df.i$exp2))
dist(rbind(df.o$exp1, df.o$exp2))



FTH1_negation	UBA52_negation
FCRLA	HLA-DRA
TSC22D3	HLA-DRA

CD37	HLA-DQA1


x.seq <- 1
df.all <- data.frame()
for (x.seq in 1:nrow(makers.prauc[[5]])) {
  gene.c <- makers.prauc[[5]][x.seq,]
  df <- data.frame(exp1 = cbmc@assays$RNA@data[gene.c$Gene1,],
                   exp2 = cbmc@assays$RNA@data[gene.c$Gene2,],
                   id = as.character(cbmc@active.ident))
  df.i <- df[df$id == "5", ]
  df.o <- df[df$id != "5", ]
  # print(gene.c)
  df.s <- data.frame(gene.c$Gene1, gene.c$Gene2, cor(df.i$exp1, df.i$exp2), cor(df.o$exp1, df.o$exp2))
  colnames(df.s) <- c("gene1", "gene2", "cor.i", "cor.o")
  df.all <- rbind(df.all, df.s)
}

cbmc <- makeid(cbmc, "6")
df <- data.frame(exp1 = cbmc@assays$RNA@data["CD19",],
                 exp2 = cbmc@assays$RNA@data["HLA-DRA",],
                 id = as.character(cbmc@active.ident))

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))

df <- data.frame(exp1 = cbmc@assays$RNA@data["CD79B",],
                 exp2 = cbmc@assays$RNA@data["HLA-DRA",],
                 id = as.character(cbmc@active.ident))

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))

normalize <- function(x, ...) {
    return((x - min(x, ...)) /(max(x, ...) - min(x, ...)))
}

x <- c(1, NA, 2, 3)

normalize(x, na.rm = TRUE)

rownames(markers.wilcox[[6]])

Detect_combine_markers.1 <- function(scrna, id, geneset, step = 0.1, max.gene = NULL){
  gene.combn <- t(combn(geneset, 2))
  gene.combn.prauc <- data.frame()

  for (gene.iter in 1:length(gene.combn[,1])) {
    
    genes <- gene.combn[gene.iter,]
    gene1 <- genes[1]
    gene2 <- genes[2]
    
    df <- data.frame(exp1 = scale(scrna@assays$RNA@data[gene1,]),
                     exp2 = scale(scrna@assays$RNA@data[gene2,]),
                     id = as.character(scrna@active.ident))
  
    df.i <- df[df$id == id, ]
    df.o <- df[df$id != id, ]
    
    # x.fc1 <- round((mean(df.i$exp1) + 0.001)/(mean(df.o$exp1) + 0.001), 3)
    # x.fc2 <- round((mean(df.i$exp2) + 0.001)/(mean(df.o$exp2) + 0.001), 3)
    
    x.dist <- as.numeric(dist(rbind(df.o$exp1, df.o$exp2))/dist(rbind(df.i$exp1, df.i$exp2)))
    
    # x.dist <- x.dist*((x.fc1*x.fc2))

    de <- data.frame(gene1, gene2, x.dist)
    colnames(de) <- c("Gene1", "Gene2", "dist")
    gene.combn.prauc <- rbind(gene.combn.prauc, de)
  }
  gene.combn.prauc <- gene.combn.prauc[order(gene.combn.prauc$dist, decreasing = T),]
  return(gene.combn.prauc)
}

```

```{r}
x.dist.6 <- Detect_combine_markers.1(cbmc, "6", rownames(df.6)[1:50])
```


```{r}
cbmc <- makeid(cbmc, "6")
df <- data.frame(exp1 = cbmc@assays$RNA@data["CD79B",],
                 exp2 = cbmc@assays$RNA@data["CD74",],
                 id = as.character(cbmc@active.ident))

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))

df <- data.frame(exp1 = scale(cbmc@assays$RNA@data["HLA-DRA",]),
                 exp2 = scale(cbmc@assays$RNA@data["LTB",]),
                 id = as.character(cbmc@active.ident))

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))

df <- data.frame(exp1 = cbmc@assays$RNA@data["HLA-DRA",],
                 exp2 = cbmc@assays$RNA@data["FCRLA",],
                 id = as.character(cbmc@active.ident))

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))


```

```{r}
id <- "6"
df <- data.frame(exp1 = normalize(cbmc@assays$RNA@data["CD79B",]),
                 exp2 = normalize(cbmc@assays$RNA@data["CD74",]),
                 id = as.character(cbmc@active.ident))

ggplot(df) +
  geom_point(aes(exp1, exp2, col = id))

df.i <- df[df$id == id, ]
df.o <- df[df$id != id, ]

df[df$exp1 >  quantile(df.i$exp1, 0.5), ]$exp1 <- 1
df[df$exp1 != 1, ]$exp1 <- 0

df[df$exp2 >  quantile(df.i$exp2, 0.5), ]$exp2 <- 1
df[df$exp2 != 1, ]$exp2 <- 0

df.i <- df[df$id == id, ]
df.o <- df[df$id != id, ]

dist(rbind(df.o$exp1, df.o$exp2))
dist(rbind(df.i$exp1, df.i$exp2))


plot(df$exp1, df$exp2)


dist(rbind(df.o$exp1, df.o$exp2))/dist(rbind(df.i$exp1, df.i$exp2))

df <- data.frame(exp1 = scale(cbmc@assays$RNA@data["RPSA",]),
                 exp2 = scale(cbmc@assays$RNA@data["HLA-DRA",]),
                 id = as.character(cbmc@active.ident))

df.i <- df[df$id == id, ]
df.o <- df[df$id != id, ]

df[df$exp1 >  quantile(df.i$exp1, 0.5), ]$exp1 <- 1
df[df$exp1 != 1, ]$exp1 <- 0

df[df$exp2 >  quantile(df.i$exp2, 0.5), ]$exp2 <- 1
df[df$exp2 != 1, ]$exp2 <- 0

df.i <- df[df$id == id, ]
df.o <- df[df$id != id, ]


dist(rbind(df.o$exp1, df.o$exp2))/dist(rbind(df.i$exp1, df.i$exp2))
```

```{r}
get_PRAUC_matrix_combine_markers.1 <- function(scrna, gene1,  gene2, id, step = 0.01){
  data.mat.surf <- data.frame(gene1 = scrna@assays$RNA@data[gene1,],
                              gene2 = scrna@assays$RNA@data[gene2,],
                              id = as.character(makeid(scrna, id)@active.ident))
  gene.prauc <- data.frame(x.pre <- c(),
                           x.rec <- c())
  data.id <- data.mat.surf[data.mat.surf$id == id,]
  data.other <- data.mat.surf[data.mat.surf$id != id,]
  
  x.seq <- seq(0.05, 0.95, step)

  for (x.val in quantile(data.id$gene1, x.seq)) {
    for (y.val in quantile(data.id$gene2, x.seq)) {
      tp <- sum(data.id$gene1 > x.val & data.id$gene2 > y.val)
      fp <- sum(data.other$gene1 > x.val & data.other$gene2 > y.val)
      fn <- sum(data.id$gene1 <= x.val | data.id$gene2 <= y.val)
      x.pre <- tp/(tp + fp)
      x.rec <- tp/(tp + fn)
      de <- data.frame(x.pre, x.rec)
      gene.prauc <- rbind(gene.prauc, de)
    }
  }
  gene.prauc <- gene.prauc[complete.cases(gene.prauc), ]
  gene.prauc <- gene.prauc[order(gene.prauc$x.rec), ]
  return(gene.prauc)
}
df <- get_PRAUC_matrix_combine_markers.1(cbmc, "CD79B", "CD74", "6", step = 0.1)

plot(df$x.rec, df$x.pre)

ggplot(df)+
  geom_line(aes(x.rec, x.pre), se = FALSE)

df <- get_PRAUC_matrix_combine_markers.1(cbmc, "FCRLA", "HLA-DRA", "6", step = 0.1)

plot(df$x.rec, df$x.pre)

ggplot(df)+
  geom_line(aes(x.rec, x.pre), se = FALSE)


```

```{r}
time <- 0:100
temp <- 20+ 0.01 * time^2 + 0.8 * time + rnorm(101, 0, 5)

# Generate first order linear model
lin.mod <- lm(cbmc@assays$RNA@data["CD79B",]~cbmc@assays$RNA@data["CD74",])

# Generate second order linear model
lin.mod2 <- lm(temp~I(time^2)+time)

# Calculate local regression
ls <- loess(cbmc@assays$RNA@data["CD79B",]~cbmc@assays$RNA@data["CD74",])

# Predict the data (passing only the model runs the prediction 
# on the data points used to generate the model itself)
pr.lm <- predict(lin.mod)
pr.lm2 <- predict(lin.mod2)
pr.loess <- predict(ls)

par(mfrow=c(2,2))
plot(cbmc@assays$RNA@data["CD79B",], cbmc@assays$RNA@data["CD74",])
lines(pr.lm~cbmc@assays$RNA@data["CD79B",], col="blue", lwd=2)

plot(time, temp, "l", las=1, xlab="Time", ylab="Temperature")
lines(pr.lm2~time, col="green", lwd=2)

plot(cbmc@assays$RNA@data["CD79B",], cbmc@assays$RNA@data["CD74",])
lines(pr.loess~cbmc@assays$RNA@data["CD79B",], col="red", lwd=2)

  data.mat.surf <- data.frame(gene1 = cbmc@assays$RNA@data["CD79B",],
                              gene2 = cbmc@assays$RNA@data["CD74",])
  
  # data.mat.surf <- data.mat.surf[data.mat.surf$gene1*data.mat.surf$gene2 != 0, ]
  ggplot(data.mat.surf)+
    geom_point(aes(gene1, gene2))+
    geom_smooth(aes(gene1, gene2), method = lm)
  data.mat.surf <- data.mat.surf[data.mat.surf$gene1*data.mat.surf$gene2 != 0, ]
  ggplot(data.mat.surf)+
    geom_point(aes(gene1, gene2))+
    geom_smooth(aes(gene1, gene2))
  plot(fit1,fit)
  
  qplot(gene1,gene2,data=data.mat.surf) + stat_smooth(aes(outfit=fit<<-..y..)) + stat_smooth(aes(outfit=fit1<<-..x..))
  fit
  fit1
  
  plot(fit1,fit)
```


```{r fig.width=10, fig.height=8}
scrna <- cbmc
for (x.cluster in seq(1,8)) {
  genes <- read.csv(paste("/home/ronghui/project/dbmaker/data/cluster_", x.cluster, "_pair_final_ranking.csv", sep = ""))
  genes <- c(genes[1,2], genes[1,3])
  
  # x.df <- get_PRAUC_matrix_combine_markers(scrna = scrna, gene1 = genes[1], gene2 = genes[2], id = x.cluster, step = 0.1)
  # x.df$method <- "COMET"
  
  if (!grepl("_negation", genes[1])) {
    if (!grepl("_negation", genes[2])) {
      gene.prauc <- get_PRAUC_matrix_combine_markers(scrna = scrna, gene1 = genes[1], gene2 = genes[2], id = x.cluster, step = 0.01)
      }else{
        genes[2] <- gsub("_negation", "", genes[2])
        gene.prauc <- get_PRAUC_matrix_combine_markers_neg_pos(scrna = scrna, gene1 = genes[1], gene2 = genes[2], id = x.cluster, step = 0.01)
      }
    }else{
      if (!grepl("_negation", genes[2])) {
        genes[1] <- gsub("_negation", "", genes[1])
        gene.prauc <- get_PRAUC_matrix_combine_markers_neg_pos(scrna = scrna, gene1 = genes[2], gene2 = genes[1], id = x.cluster, step = 0.01)
      }else{
        genes[1] <- gsub("_negation", "", genes[1])
        genes[2] <- gsub("_negation", "", genes[2])
        gene.prauc <- get_PRAUC_matrix_combine_markers_neg(scrna = scrna, gene1 = genes[1], gene2 = genes[2], id = x.cluster, step = 0.01)
      }
    }

  x.df <- gene.prauc
  x.df$method <- "COMET"
  # g <- ggplot() + geom_line(gene.prauc.comet, mapping = aes(x.rec, x.pre, color = method)) + xlim(c(0,1)) + ylim(c(0,1))
  
  df.split <- makers.prauc[[x.cluster]]
  genes <- c(df.split[1,1], df.split[1,2])
  gene1 <- genes[1]
  gene2 <- genes[2]
  
  Direction.c <- paste(df.split[1, ]$Direction1, df.split[1, ]$Direction2, sep = "")
  if (Direction.c == "++") {
    gene.prauc <- get_PRAUC_matrix_combine_markers(scrna = scrna, gene1 = gene1, gene2 = gene2, id = x.cluster, step = 0.01)
  }else if (Direction.c == "+-") {
    gene.prauc <- get_PRAUC_matrix_combine_markers_neg_pos(scrna = scrna, gene1 = gene1, gene2 = gene2, id = x.cluster, step = 0.01)
  }else if (Direction.c == "-+") {
    gene.prauc <- get_PRAUC_matrix_combine_markers_neg_pos(scrna = scrna, gene1 = gene2, gene2 = gene1, id = x.cluster, step = 0.01)
  }else{
    gene.prauc <- get_PRAUC_matrix_combine_markers_neg(scrna = scrna, gene1 = gene1, gene2 = gene2, id = x.cluster, step = 0.01)
  }
  
  x.df.2 <- gene.prauc
  x.df.2$method <- "PRAUC"
  
  x.df <- rbind(x.df, x.df.2)

  print(ggplot() + geom_line(x.df, mapping = aes(x.rec, x.pre, col = method)) + ggtitle(paste(x.cluster))+ 
          xlim(c(0,1)) + ylim(c(0,1)))
}
```


# Dotplot of Combine markers

```{r fig.width=10, fig.height=5}
for (x.cluster in seq(1,8)) {
  scrna <- makeid(scrna, x.cluster)
  genes <- read.csv(paste("/home/ronghui/project/dbmaker/data/cluster_", x.cluster, "_pair_final_ranking.csv", sep = ""))
  genes <- c(genes[1,2], genes[1,3])
  if (!grepl("_negation", genes[1])) {
    gene1.direc <- "+"
  }else{
    gene1.direc <- "-"
  }
  
  if (!grepl("_negation", genes[2])) {
    gene2.direc <- "+"
  }else{
    gene2.direc <- "-"
  }
  genes <- gsub("_negation", "", genes)
  gene1 <- genes[1]
  gene2 <- genes[2]
  
  p1 <- plot_grid_2(cbmc, gene1, gene2, gene1.direc, gene2.direc, x.cluster, return.obj = T) + ggtitle("COMET")
  

  df.split <- makers.prauc[[x.cluster]]
  genes <- c(df.split[1,1], df.split[1,2])
  gene1 <- genes[1]
  gene2 <- genes[2]
  
  p2 <- plot_grid_2(cbmc, gene1, gene2, df.split$Direction1[1], df.split$Direction2[1], x.cluster, return.obj = T) + ggtitle("PRAUC")
  
  print(p1 | p2)
}
```





# Umap plot of combine markers

```{r fig.height = 7, fig.width=18}
Idents(cbmc) <- "seurat_clusters"
plot_marker_c_umap(cbmc, "TCL1A", "CD79B", "+", "+", "6")
scrna <- cbmc
Idents(scrna) <- "seurat_clusters"
for (x.cluster in seq(1,8)) {
  genes <- read.csv(paste("/home/ronghui/project/dbmaker/data/cluster_", x.cluster, "_pair_final_ranking.csv", sep = ""))
  genes <- c(genes[1,2], genes[1,3])
  if (!grepl("_negation", genes[1])) {
    gene1.direc <- "+"
  }else{
    gene1.direc <- "-"
  }
  
  if (!grepl("_negation", genes[2])) {
    gene2.direc <- "+"
  }else{
    gene2.direc <- "-"
  }
  genes <- gsub("_negation", "", genes)
  gene1 <- genes[1]
  gene2 <- genes[2]
  
  p1 <- plot_marker_c_umap(scrna, gene1, gene2, gene1.direc, gene2.direc, x.cluster) + ggtitle("COMET")
  

  df.split <- makers.prauc[[x.cluster]]
  genes <- c(df.split[1,1], df.split[1,2])
  gene1 <- genes[1]
  gene2 <- genes[2]
  
  p2 <- plot_marker_c_umap(scrna, gene1, gene2, df.split$Direction1[1], df.split$Direction2[1], x.cluster) + ggtitle("PRAUC")
  
  print(p1 | p2)
}
```

```{r}
cbmc.enhance <- enhance_seurat_wrapper(cbmc)
id <- "5"
gene1 <- "MYL3"
gene2 <- "FTH1"

df <- data.frame(exp1 = cbmc.enhance[gene1,],
                 exp2 = cbmc.enhance[gene2,],
                 id = as.character(makeid(scrna, id)@active.ident))

ggplot(df) + geom_point(aes(exp1, exp2, col = id))

df <- data.frame(exp1 = cbmc@assays$RNA@data[gene1,],
                 exp2 = cbmc@assays$RNA@data[gene2,],
                 id = as.character(makeid(scrna, id)@active.ident))

ggplot(df) + geom_point(aes(exp1, exp2, col = id))

```




# step by step (Maximam Recall approach)

```{r}
# markers.max_recall <- list()
# for (x.cluster in seq(1,8)) {
#   markers.i <- marker_stepbystep(cbmc, x.cluster, depth = 2, markers.allset)
#   markers.max_recall[[x.cluster]] <- markers.i
# }
# save(markers.max_recall, file = "first8.stepbystep.rds")
load(file = "first8.stepbystep.rds")
for (x.cluster in seq(1,8)) {
  markers.i <- markers.max_recall[[x.cluster]]
  print(grid_plot(cbmc, markers.i, x.cluster))
}
```                                                                                                                                                                                               




